# Generated by Django 5.0.6 on 2024-06-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petstoreapp', '0004_orderdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orderdetail',
            new_name='order',
        ),
    ]
